<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => '首页',
    'username'=>'用户名',
    'Log in' => '登录',
    'Log out' => '退出',
    'Sign up' => '注册',
    'Sign up now!' => '注册',
    'Password' => '密码',
    'Captcha' => '验证码',
    'Email' => '邮箱',
    'Inbox' => '收件箱',
    'Please fill out your email. A link to reset password will be sent there.' => '请填写您注册时使用的邮箱，将会发送一封邮件到您注册邮箱那里。',
];
